pytest-dev/pytest-testinfra

Vagrantfile
doc/source/backends.rst
doc/source/index.rst
images/debian_jessie/Dockerfile
testinfra/backend/__init__.py
testinfra/backend/docker.py
testinfra/backend/local.py
testinfra/plugin.py
testinfra/test/integration/test_centos_7.py
testinfra/test/integration/test_fedora_21.py
testinfra/test/integration/test_jessie.py
testinfra/test/integration/test_trusty.py
testinfra/test/integration/test_wheezy.py
tox.ini

Docker backend using docker native client.
Usage: testinfra --connection=docker --hosts=debian:jessie
For each test function, testinfra will spawn a container, run function
on it, then kill and remove container.

Docker backend

---

.travis.yml
CONTRIBUTING.rst
Vagrantfile
tox.ini

http://blog.travis-ci.com/2015-08-19-using-docker-on-travis-ci/

Use vagrant and docker on travis

---

doc/source/modules.rst
testinfra/modules/__init__.py
testinfra/modules/socket.py
testinfra/plugin.py
testinfra/test/integration/test_jessie.py
testinfra/test/test_socket.py

This is a WIP of a new Socket module.
TODO: BSD/Darwin

New Socket module

---

testinfra/backend/paramiko.py

Obey setting "StrictHostKeyChecking no" in ssh-config

---

doc/source/modules.rst
testinfra/modules/__init__.py
testinfra/modules/process.py
testinfra/plugin.py
testinfra/test/integration/test_centos_7.py
testinfra/test/integration/test_fedora_21.py
testinfra/test/integration/test_jessie.py
testinfra/test/integration/test_trusty.py
testinfra/test/integration/test_wheezy.py

New process module

---

testinfra/backend/ansible.py
testinfra/test/integration/test_jessie.py
testinfra/utils/ansible_runner.py
testinfra/utils/ssh_config_to_ansible_inventory.py
tox.ini

Ansible backend supports ansible v2

---

testinfra/modules/systeminfo.py

SystemInfo: Fix os detection on Centos/RHEL 6

---

images/debian_jessie/Dockerfile
testinfra/modules/package.py
testinfra/test/integration/test_jessie.py

handle where package is on hold by using sed regexp

Fix package version for packages on hold in dpkg

---

doc/source/backends.rst
doc/source/modules.rst
images/debian_jessie/Dockerfile
testinfra/backend/__init__.py
testinfra/backend/base.py
testinfra/backend/local.py
testinfra/modules/__init__.py
testinfra/modules/sudo.py
testinfra/plugin.py
testinfra/test/conftest.py
testinfra/test/test_backends.py
testinfra/test/test_modules.py

This module implement a context manager to run portion of code with
sudo.
Closes #93

New sudo module

---

images/debian_jessie/Dockerfile
testinfra/modules/user.py
testinfra/test/test_modules.py

User: method to check for expiration

---

testinfra/backend/ansible.py
testinfra/modules/ansible.py
testinfra/test/test_modules.py
testinfra/utils/ansible_runner.py

Ansible: Fix error reporting when ansible call is skipped

---

testinfra/modules/package.py

Package: look for dpkg-query to detect apt based systems

---

.travis.yml
CONTRIBUTING.rst

The cache trick doesn't work anymore:
https://github.com/docker/docker/issues/20316

tests: remove notes about pulling images

---

requirements.txt

[pkg] blacklist pytest 3.0.2

---

testinfra/backend/ansible.py
testinfra/backend/base.py
testinfra/backend/paramiko.py
testinfra/backend/salt.py
testinfra/backend/ssh.py

lazy parse stdout/stderr bytes and fallback to system encoding.
Closes #140
Closes #113

workaround encoding issues in ansible backend

---

doc/source/modules.rst
images/debian_jessie/Dockerfile
testinfra/modules/__init__.py
testinfra/modules/pip.py
testinfra/plugin.py
testinfra/test/test_modules.py

Check installed and outdated packages using pip.
Virtualenv support.
Closes #117

New PipPackage module

---

testinfra/test/test_modules.py

Bump version to get CI working

Bump ssh server on fedora docker image

---

doc/source/backends.rst
testinfra/backend/__init__.py
testinfra/backend/base.py
testinfra/backend/docker.py
testinfra/backend/kubectl.py

I wanted to test container deployments in Kubernetes, so I hacked together a backend. I've manually functionally tested it, but I'm not sure what kind of automated testing is desired/required, or whether you want to make Kubernetes (minikube, etc.) a test dependency. Looking for guidance on this.
I'll be happy to update the docs. Thanks!

Add a kubectl backend

---

test-requirements.txt
testinfra/backend/__init__.py
testinfra/backend/ansible.py
testinfra/backend/paramiko.py
testinfra/backend/salt.py
testinfra/test/test_backends.py
testinfra/test/test_modules.py
testinfra/utils/ansible_runner.py
tox.ini

import backend classes using importlib.import_module(), this simplify
handling of optional requirements and reduce import time.

backends: dynamic import

---

requirements.txt

[pkg] add dependency on importlib for python 2.6

---

testinfra/utils/ansible_runner.py

When using ansible backend against remote hosts that require privilege
escalation, the run fails because of 'None' value in
self.options.become_user field of AnsibleRunnerV2 class.
The Ansible tool addresses this issue by running
ansible.cli.CLI.normalize_become_options() method, which is not static
and requires a CLI object.
To address the issue in AnsibleRunnerV2 the proposed change embeds CLI
object to prepare correct options structure.
Fixes #174

Fix empty become_user option

---

doc/source/api.rst

This is just a docs change. I noticed a small typo ('fonction') and subsequently tweaked the sentence a bit.

Typo fix and small wording change

---

testinfra/modules/service.py

When running testinfra over ssh with unprivileged user, 'service'
command may not be found because not in $PATH, in this case try to find
it in /sbin/service or /usr/sbin/service.
Closes #211

service: allow to find service outside of $PATH

---

doc/source/backends.rst
doc/source/modules.rst
test/conftest.py
test/test_backends.py
testinfra/backend/__init__.py
testinfra/backend/base.py
testinfra/backend/paramiko.py
testinfra/backend/ssh.py
testinfra/backend/winrm.py

CC @gtmanfred can you review this and tell me if you're ok ?

Fixes for winrm & doc

---

.travis.yml
test/test_modules.py
testinfra/utils/ansible_runner.py
tox.ini

Mostly VariableManager/Inventory refactor.
Relevant commit in ansible:
https://github.com/ansible/ansible/commit/8f97aef1a365cbbbb822d6d09f96af17a076b295
Closes #249

Support for ansible >= 2.4

---

doc/source/_static/logo.svg
doc/source/conf.py

The font is nto exactly the same as the one in the PNG file, but hey.

replace the png logo file by an svg one

---

testinfra/plugin.py

Fix running testinfra within a suite using doctest

---

doc/source/modules.rst
images/debian_jessie/Dockerfile
test/test_modules.py
testinfra/modules/__init__.py
testinfra/modules/iptables.py

Addresses one of the few features I currently use in serverspec that testinfra lacks. Open to suggestions on code. Thoughts?

iptables module

---

testinfra/backend/paramiko.py

Currently the ssh_config option RequireTTY is not used when using the
paramiko backend with an ssh config file.  This option is useful
when using sudo and connecting to hosts which have the requiretty
option set in sshd_config. Setting requiretty in sshd_config is no
longer a common default, but it is frequently on older distributions and
in some 'hardened' distributions.
This change causes paramiko to use Channel.get_pty() to request a
pseudo-terminal if the RequireTTY option is specified in a provided
ssh_config.
This allows addressing
https://github.com/philpep/testinfra/issues/247
without modifying the server-side configuration.

Use the RequireTTY setting if specified in a provided SSHConfig

---

test/test_invocation.py
test/test_modules.py
testinfra/utils/ansible_runner.py

They where broken by pytest 3.3.0 new progress output.

Fix --nagios tests

---

images/alpine_35/Dockerfile
test/conftest.py
test/test_modules.py
testinfra/modules/package.py

Add support package and test for them

228 add support for alpine package manager

---

images/alpine_35/Dockerfile
pylintrc
test/conftest.py
test/test_modules.py
testinfra/modules/process.py
testinfra/modules/service.py
testinfra/modules/systeminfo.py

Add service, process, and systeminfo support for Alpine

---

test/test_modules.py
testinfra/modules/ansible.py

Add a decorator for future needs.
Closes #288

Ansible: get_variables() require using ansible backend

---

images/archlinux/Dockerfile
test/conftest.py
test/test_modules.py
testinfra/modules/package.py
testinfra/modules/systeminfo.py

Add support for Arch Linux package manager and update tests.

Add support for Arch Linux

---

testinfra/modules/pip.py

Recently-released 10.x versions of pip use a different output format by default for `pip list` (columns). Here we are switching to specify that format explicitly, making the code compatible with both 9.x and 10.x versions of pip.

Make PipPackage compatible with pip 10.x

---

test/conftest.py
test/test_modules.py
tox.ini

Wait sshd to be up before running the test.

Fix test_ssh_service for archlinux / alpine

---

doc/source/backends.rst
testinfra/backend/__init__.py
testinfra/backend/lxc.py

Copy of docker backend for LXD containers.

LXC backend

---

test/conftest.py

A getattr on the function doesn't work since pytest 4.
Looks the correct way to do this is to test the presence of "pytestmark"
attribute on the function which is either undefined or contains a list
of Marker objects.
We don't care about backward compat with older pytest versions for
testinfra own tests.

test: fix pytest 4 markers usage

---

doc/source/modules.rst
images/archlinux/Dockerfile
images/ubuntu_xenial/Dockerfile
test/test_modules.py
testinfra/modules/__init__.py
testinfra/modules/addr.py

Implemented `Addr` module. 
Parameters:
- `name`: hostname or IP address
Properties:
- `is_resolvable`: check if host is resolvable using either `/etc/hosts` or DNS, plain IP addresses are always resolvable (they are already resolved after all)
- `ipv4_addresses`: return list of IPv4 addresses corresponding to hostname
- `is_reachable`: check if host is reachable using `ping`
- `port(value).is_reachable`: check if given port is reachable using TCP
Documentation and tests are included!
This is an implementation for #358

Addr module

---

.travis.yml
setup.py
testinfra/__init__.py
testinfra/backend/base.py
testinfra/modules/__init__.py
testinfra/plugin.py
testinfra/utils/__init__.py
testinfra/utils/ansible_runner.py
tox.ini

Basically drop deprecated code and old ansible versions support.

testinfra v2.0

---

testinfra/modules/docker.py

This add possibility to list containers with filtering support.

docker: implement get_containers()

---

testinfra/host.py

__getattr__ should only raise AttributeError

---

testinfra/modules/socket.py

socket: fix parsing of ipv6 addresses

---

test/test_modules.py

Following on from f29de6fd31cff9cc5cb58cd7654d86f5fc7ea8a3, remove
some parts of the ansible test cases handling ansible version 1 for
skipped tasks in check-mode.

Remove Ansible V1 support from test cases

---

test/test_backends.py
testinfra/backend/ansible.py
testinfra/backend/paramiko.py
testinfra/utils/ansible_runner.py

Except if host is explicitly "localhost".
This behave like plain ansible and testinfra < 3.X
Related to #439

ansible: empty or no inventory should not execute on any hosts

---

doc/source/backends.rst
testinfra/utils/ansible_runner.py

Copy of LXC backend for LXD containers.
Clone from https://github.com/philpep/testinfra/pull/334

LXD Backend

---

testinfra/backend/paramiko.py

Support the ProxyCommand in paramiko backend

Support the ProxyCommand in paramiko backend

---

doc/source/backends.rst
test/test_backends.py
testinfra/backend/__init__.py
testinfra/backend/kubectl.py

This should address the #459 issue.
Missing things:
Unfortunately I did not manage to run the test suite locally, so I am trying to use the automation to do that for me. In the meantime I will try again updating the thread with problems I am encountering.
Thanks!

Add kubeconfig support for kubectl backend

---

.travis.yml

travis: use stages and deploy to pypi

---

doc/source/modules.rst
test/test_modules.py
testinfra/modules/__init__.py
testinfra/modules/environment.py

add environment module

---

testinfra/plugin.py

ansible: add a --force-ansible global flag to the command line

---

.editorconfig
MANIFEST.in

Add an EditorConfig configuration file to easy configure some code style
parameters.
+info: https://editorconfig.org/

EditorConfig support

---

doc/source/backends.rst
test/test_backends.py
testinfra/backend/__init__.py
testinfra/backend/openshift.py

I just copied the Kubernetes backend. I've tested it on a real OpenShift deployment.

OpenShift backend

---

testinfra/modules/process.py

Use set literals.

---

doc/source/examples.rst

There is no testinfra command, there is only py.test

Update vagrant example

---

doc/source/backends.rst
doc/source/modules.rst
testinfra/backend/__init__.py
testinfra/backend/podman.py
testinfra/modules/__init__.py
testinfra/modules/podman.py
testinfra/plugin.py

Podman is another container management tool, similar in function to
Docker (but different in operation).  This adds a podman module, a
podman backend, and updates the docs accordingly.

Add preliminary support for podman.

---

testinfra/host.py

Make Host repr more friendly

---

CONTRIBUTING.rst
README.rst
doc/source/backends.rst
doc/source/invocation.rst
doc/source/support.rst

The editorconfig settings trimmed also some trailing whitespace.

Updated links to https and new locations.

---

CONTRIBUTING.rst
setup.cfg
testinfra/modules/file.py

I removed the 3.4 classifier from `setup.cfg` as well, although no code changes were made due to this.

Contribuing guide

---

doc/source/backends.rst
test/test_backends.py
testinfra/backend/__init__.py
testinfra/backend/kubectl.py

I have not run the tests as I couldn't work out how to install the deps from my locked down environment.
Fixes #554

Allow kubernete context to be supplied #554

---

testinfra/modules/service.py

Hi,
See #567 for the context of changes.
And see that comment from 2017 for the documentation part : https://github.com/philpep/testinfra/pull/265#issuecomment-346306163

Fix#567 : Implement is_masked in Service and add doc for is_masked and is_valid

---

.travis.yml
CONTRIBUTING.rst
README.rst
doc/source/conf.py
doc/source/support.rst
setup.cfg
test/conftest.py

For name of docker images used during tests, just use "testinfra" prefix.

Rename philpep/testinfra to pytest-dev/pytest-testinfra

---

test/test_modules.py
testinfra/modules/supervisor.py

Hello
Closes #536.
```python
gunicorn = host.supervisor("gunicorn", "/usr/bin/supervisorctl", "/etc/supervisor/supervisord.conf")
assert gunicorn.status == "RUNNING"
```
Best

Add a supervisorctl path option and ability to pass a configuration file path 

---

testinfra/utils/ansible_runner.py

Ansible options can now consistently be specified in the `ansible.cfg`
configuration file, in group or host variables or in environment variables, the
latter taking precedence on the former.
| Configuration File                        | Host Variable         | Environment           |
| ----------------------------------------- | --------------------- | --------------------- |
| `[privilege_escalation]`<br>`become`      | `ansible_become`      | `ANSIBLE_BECOME`      |
| `[privilege_escalation]`<br>`become_user` | `ansible_become_user` | `ANSIBLE_BECOME_USER` |
| `[defaults]`<br>`remote_port`             | `ansible_port`        | `ANSIBLE_REMOTE_PORT` |
| `[defaults]`<br>`remote_user`             | `ansible_user`        | `ANSIBLE_REMOTE_USER` |
Signed-off-by: Benoît Knecht …

ansible: Support environment variables

---

images/debian_bullseye/Dockerfile
test/test_modules.py
testinfra/modules/user.py

add feature for checking user password min/max days

---

testinfra/backend/salt.py

See https://github.com/pytest-dev/pytest-testinfra/pull/566. It's the same PR but it's now updated with latest changes from the master branch.

Fix Salt decode error

---

.github/workflows/tox.yml
CONTRIBUTING.rst
setup.cfg
tox.ini

I also added the missing classifiers for Python 3.9, as well as Python 3.10.

Add support for Python 3.10.

---

testinfra/modules/package.py

Adding AlmaLinux and Rocky to package.py for package detection

Adding AlmaLinux and Rocky to package.py

---

testinfra/modules/package.py

Adding CloudLinux to package.py for package detection

Adding Cloudlinux to package.py

---

testinfra/backend/paramiko.py

The `include` statement in the ssh config is now supported when using paramiko as the backend
This is a relatively simple change, but it allows my overly complicated ssh setup to work out of the box.  Please let me know if there is anything I need to change so this can be merged.

Improved ssh config support in Paramiko backend

---

testinfra/host.py

Fix the `command -v` exit status handling to account for dash being `/bin/sh` (this is e.g. the default on Debian).  Unlike bash, dash exits with status 127 if the requested program does not exist -- and testinfra wrongly interpreted that as `command` being unavailable.
Instead of attempting to use `command -v` and `which` in order, peform an additional (cached) `command -v command` invocation to determine whether `command` is available.  Furthermore, assume that `command -v` can return any non-zero status for command not existing, per POSIX.
This fixes exists() and find_command() raising an exception on systems using dash as `/bin/sh` and lacking `which(1)`.
Fixes #668

Fix `command -v` compatibility with dash shell

---

test-requirements.txt

test-requirements.txt:
Remove mock from test requirements as it is not used.

Remove mock from test requirements

---

images/rockylinux8/Dockerfile
test/conftest.py
test/test_backends.py
test/test_modules.py
testinfra/modules/package.py

Drop support for CentOS 7 in tests and add RockyLinux 8

---

testinfra/modules/docker.py

Hi,
I've added is_restarting to the docker module regarding issue #659.
Fix #659

Add is_restarting in docker module

---

testinfra/modules/systeminfo.py

check if key "distribution" exists

---

testinfra/modules/group.py

Hi,
this PR contains `Group.user_list` which returns a list of user names that are members of this group.
Regards,
Carsten

Add propery Group.user_list

---

doc/source/modules.rst
testinfra/modules/__init__.py
testinfra/modules/pip.py

Drop deprecated module PipPackage

---

testinfra/backend/ssh.py
testinfra/utils/ansible_runner.py

Add check for the existance of ssh control path directory

---

README.rst

The project is currently not actively maintained, this notice help to set clear expectations for users & contributors.
Closes #790

Add a maintenance notice
