testinfra/modules/package.py
Noticed that package.is_installed didn't seem to properly verify that the package was actually installed. So here's a quick fix.
=> Properly check package.is_installed tests for rpm based system

README.rst, doc/source/api.rst, testinfra/modules/file.py, testinfra/test/test_file.py
**This is a backwards incompatible change**
Currently with `testinfra`, `File.mode` is provided as a decimal integer `644`, but it should be represented as an octal integer `0o644`, since this is how it is given to us by the os.
This change aligns with the Python standard library which uses an octal integer for `os.stat`.
```python
import os
import stat
s = os.stat('/etc/passwd')
mode = stat.S_IMODE(s.st_mode)
mode == 420
oct(420) == '0644'  # '0o644' in python 3
```
This also means we can utilize the file mode octal constants in the `stat` module for tests.
```python
import stat
def test_user_readable(File):
passwd = File('/etc/passwd')
assert passwd.mode & stat.S_IRUSR
def test_not_other_executable(File):
passwd = File('/etc/passwd')
assert not passwd.mode & stat.S_IXOTH
def …
```
=> Make File.mode be in octal form

testinfra/modules/service.py
In case of symlink path, find will start from symlink target.
```
[root@ae2c458b4cac /]# ls -l /etc/rc?.d
lrwxrwxrwx 1 root root 10 Jun 15 19:21 /etc/rc0.d -> rc.d/rc0.d
lrwxrwxrwx 1 root root 10 Jun 15 19:21 /etc/rc1.d -> rc.d/rc1.d
lrwxrwxrwx 1 root root 10 Jun 15 19:21 /etc/rc2.d -> rc.d/rc2.d
lrwxrwxrwx 1 root root 10 Jun 15 19:21 /etc/rc3.d -> rc.d/rc3.d
lrwxrwxrwx 1 root root 10 Jun 15 19:21 /etc/rc4.d -> rc.d/rc4.d
lrwxrwxrwx 1 root root 10 Jun 15 19:21 /etc/rc5.d -> rc.d/rc5.d
lrwxrwxrwx 1 root root 10 Jun 15 19:21 /etc/rc6.d -> rc.d/rc6.d
```
```
[root@ae2c458b4cac /]# find /etc/rc?.d -name 'S??sssd'
[root@ae2c458b4cac /]# find /etc/rc?.d/ -name 'S??sssd'
/etc/rc2.d/S12sssd
/etc/rc3.d/S12sssd
/etc/rc4.d/S12sssd
/etc/rc5.d/S12sssd
[root@ae2c458b4cac /]#
```
=> Added slash at the end of rc?.d path

testinfra/modules/interface.py
The __call__ method was misnamed, preventing it from actually being
called.  Details in #43.
=> 'LinuxInterface' object is not callable

testinfra/backend/paramiko.py
When the connection is dropped (for instance if the target host is
restarted between tests), paramiko raises
"paramiko.ssh_exception.SSHException: SSH session not active". In this
case we try to reconnect (once).
=> Paramiko: Handle closed session

testinfra/modules/puppet.py
When calling facter, make sure the puppet facts are included in the output.
=> Return puppet facts when calling Facter

CONTRIBUTING.rst, README.rst
As per [their blog post of the 27th April](https://blog.readthedocs.com/securing-subdomains/) ‘Securing subdomains’:
> Starting today, Read the Docs will start hosting projects from subdomains on the domain readthedocs.io, instead of on readthedocs.org. This change addresses some security concerns around site cookies while hosting user generated data on the same domain as our dashboard.
Test Plan: Manually visited all the links I’ve modified.
=> Convert readthedocs links for their .org -> .io migration for hosted projects

testinfra/backend/paramiko.py
necesary to make the following work properly 
testinfra --connection=ssh --sudo --ssh-config=~/.ssh/config
=> expand path when using --ssh-config

testinfra/backend/salt.py
Running tests in parallel with xdist used to fail with the Salt backend
because each worker would get a list of tests in a different order.
This commit ensures that the Salt backend returns hosts in a
deterministic order.
=> Fix parallel execution with Salt backend

testinfra/modules/socket.py
It's available in most places, but it might not be available in docker containers so add a clarifying note to the docs -- save someone a bit of time if they get this error:
```
ipdb> Socket("tcp://80").is_listening
*** Failed: Unexpected exit code 127 for CommandResult(command=b'netstat -n -l -t', exit_status=127, stdout=b'', stderr=b'/bin/sh: 1: netstat: not found\n')
```
=> Note that Socket module requires netstat

doc/source/backends.rst
I was struggling for a while to figure out how to set the username Ansible should use to connect. Rather than modifying the inventory / ansible.cfg as suggested in (here)[https://github.com/philpep/testinfra/issues/53], I thought it would make more sense to use one of Ansible's many [configurable environment variables](https://github.com/ansible/ansible/blob/devel/lib/ansible/constants.py).
I updated your backends doc to reflect that there is an environment variable one can use to control the remote user.
Any feedback / suggestions are gratefully accepted :).
=> Added reference to ANSIBLE_REMOTE_USER

doc/source/modules.rst, images/centos_7/Dockerfile, images/fedora/Dockerfile, testinfra/modules/command.py, testinfra/modules/package.py, testinfra/modules/service.py, testinfra/test/conftest.py
http://pubs.opengroup.org/onlinepubs/9699919799/utilities/command.html
* add exists() on Command to check if a command exists in $PATH or not
* switch to "command -v" (builtin) instead of "which"
* drop now useless installation of which in centos and fedora images
=> check for presence of commands with command -v

testinfra/modules/package.py, testinfra/test/test_modules.py
Hi
*Rationale*: I have found testinfra very useful for my work. But in my case, the relase info returned by RPM package manager is relevant for us.
This Pull Request adds an 'release' property to the Package module for package managers that support this property. Otherwise returns an `NotImplementedError` exception. This should not break any existing tests already written.
=> adding a release property to package module

testinfra/modules/base.py, testinfra/modules/systeminfo.py
I have detected that SystemInfo.type string got a hidden trailing CR.
A strip() gets away with this.
=> fixed trailing LineFeed bug

testinfra/modules/package.py
parsing rpm -qi was inefficient and ineffective. 
rpm -qi and line.split(":", 1)[1].strip()  were giving
```
>>> Package('acl').version
2.2.49                            Vendor: Red Hat, Inc.
```
While technically this starts with the same characters as the version, it has a bunch more we don't want to see and that have no business in the version string.
rpm -q --queryformat gives direct output of the values we want.
Package('acl').version == '2.2.49'
This test now works:
```
def test_package_acl(Package):
acl = Package("acl")
assert acl.is_installed
assert acl.version == '2.2.49'
assert acl.release == '6.el6'
```
=> Fix for RpmPackage

images/debian_jessie/Dockerfile, testinfra/modules/user.py, testinfra/test/test_modules.py
Issue #155 requested access to the comment (called the gecos field for historical reasons, see 'man 5 passwd' and 'man getpwent').
Very simple change that built upon the code that was already there.
=> Implementation for #155, expand User() to include gecos field

testinfra/modules/systeminfo.py
When the uname comes back as "darwin", add info about distribution and
version, as provided by the "sw_ver" utility.
At the moment it's not possible without ugly hacks to provide the code
names (Tiger, Lion, Mavericks, etc).
See
http://unix.stackexchange.com/questions/234104/get-osx-codename-from-command-line
=> Add sysinfo for macOS

images/debian_jessie/Dockerfile, testinfra/modules/sudo.py, testinfra/test/test_modules.py
If a Sudo Command fails the backend command isn't restored by the context manager. If you then run another Command in a different test method the Sudo context is still active, which may lead to it failing if that user was unprivileged.
This PR adds a test demonstrating the problem, and a fix.
Travis is failing, but I think that's for reasons unrelated to this PR- it's also [failing on the master branch](https://travis-ci.org/manics/testinfra/builds/195503413).
=> Restore backend command if sudo fails

doc/source/examples.rst
File.content returns a byte string, so the test will fail in Python 3.
=> Update example code for testing docker images

doc/source/support.rst
Added Molecule[1] to the 'Community Contributions' section of
the docs. Testinfra is a native and *default* Molecule verifier[2].
[1] http://molecule.readthedocs.io
[2] http://molecule.readthedocs.io/en/stable-1.20/verifier.html#testinfra
=> Added Molecule to docs

testinfra/modules/service.py
When a service is managed by Upstart, the "service my-service status"
command returns exit code 0 even when the service is stopped, which
means UpstartService.is_running was true even when the service wasn't
running.
So instead of relying on the exit code, match the "running" string in
the output of "status my-service".
=> Service: fix Upstart is_running test

testinfra/backend/base.py, testinfra/test/test_backends.py
By default most docker images doesn't have LANG set and
locale.getpreferredencoding() default to "ANSI_X3.4-1968" (ascii) and
generate encoding/decoding errors.
As a workaround, fallback to UTF-8 encoding.
Closes #140
=> backend: fallback to UTF-8 encoding

testinfra/test/test_modules.py, testinfra/utils/ansible_runner.py
ansible.cli.CLI is now an abstract class, use concrete class
ansible.cli.playbook.PlaybookCLI instead.
Also avoid instanciate multiple CLI, and reuse self.cli to call methods.
This fix usage with ansible >= 2.3 where abstract class ansible.cli.CLI
cannot be instanciated directly.
Closes #194
=> ansible: fix ansible.cli usage

test/test_backends.py, testinfra/backend/ansible.py, testinfra/utils/ansible_runner.py, tox.ini
Use imp.reload instead of reload
Don't attempt to encode stdout/stderr, do it in a lazy way and using
ansible 'to_bytes' which handle surrogateescape.
Closes #197
=> backend: support py3 with ansible 2.3

test/conftest.py, test/test_modules.py, testinfra/host.py
Module.get_module expect a Host, not a Backend.
Closes #204
=> host: fix use of deprecated api

testinfra/modules/service.py
Realized that we're not able to see if services are enabled on OpenBSD. With OpenBSD >= 5.8, `rcctl` now has an `ls` command where you can get output like:
```
$ rcctl ls on
check_quotas
cron
ntpd
pf
pflogd
postfix
sensuclient
sndiod
sshd
syslogd
```
=> adding checking if service is enabled for OpenBSD

doc/source/examples.rst, testinfra/backend/__init__.py, testinfra/backend/paramiko.py
Following [Rashit’s guide](https://medium.com/@syndicut/testing-salt-formulas-with-test-kitchen-and-testinfra-d2b8642e6a39#.suhe583j4) I got KitchenCI integrated with testinfra but only after some adaptions to both his and testinfra’s code. 
This MR introduces a parameter `ssh_identity_file` for the Paramiko backend and adds documentation on how to integrate testinfra into KitchenCI. It passed my local Tox and flake8 test although I had to change `py34` to `py35` in the `tox.ini`.
=> Add ssh identity override

testinfra/modules/salt.py
This is specifically useful in kitchen-salt for me, since we are putting the configs in /tmp/kitchen/etc/salt
Thanks,
Daniel
=> allow specifying a config dir for salt module

testinfra/modules/socket.py
IPv6 listening socket are actually IPv4 compatible socket.
Closes #234
=> socket: handle AF_INET6 as AF_INET4

pylintrc, test/test_backends.py, testinfra/backend/winrm.py
The winrm backend fails if the strings in it are quoted with single
quotes instead of double quotes.
@philpep I ran into problems using this on linux, probably because of the way that linux shells handle single quotes vs double quotes.
But if this gets in, it should be good for a release.
Thanks!
Daniel
=> Use a modified pipes.quote for winrm backend

testinfra/modules/service.py
initctl can exist on non upstart system (seems that git package on
centos install a 'initctl' command).
Also check for 'status' command and presence of /etc/init directory to
detect system managed by Upstart.
Closes #243
=> Service: fix Upstart detection

CHANGELOG.rst, README.rst, doc/source/backends.rst, doc/source/examples.rst, doc/source/invocation.rst, testinfra/main.py, testinfra/plugin.py
When using testinfra command, an anoying warning "Module already
imported so can not be re-written: testinfra" is displayed.
The only reason of the existence of testinfra command as a wrapper for
pytest was handling '--nagios' option that capture py.test output and
display nagios plugin compatible output *before* pytest test report.
This is now fixed by switching the output file of pytest's
terminalreporter to a in-memory temporary file.
Since the --nagios option work with py.test command, deprecate testinfra
command since it become useless and generate an anoying warning.
Closes #135
=> Fix --nagios option with py.test and deprecate testinfra command

testinfra/modules/systeminfo.py
Drop user, uid, group, gid and hostname from SystemInfo module.
They where added by mistake in 5dce243035b521b03f5ab3509b0860710b16551a
and are not part of the public api (undocumented).
Closes #260
=> SystemInfo: drop undocumented methods

testinfra/modules/file.py
While running testinfra against a Mac OS system, I noticed that
the `linked_to` test uses `readlink -f` to evaluate a canonicalized
real path by recursively following all symlinks. Though this behavior
works with GNU's `readlink`, it does not work the same way for BSD's
version. In fact, it errors out because BSD's `readlink` does not
understand the `-f` flag.
It is possible to install the GNU equivalent for `readlink` on MacOS
via Homebrew. However, it seems like poor design to force this method
to have a dependency on Homebrew.
I found a StackOverflow post showing how to recreate the behavior of
GNU's `readlink` using BSD's `readlink`. This change is based on the
solution provided in that post, which fixes the behavior of the
`linked_to` test for systems using the BSD version of …
=> Fix for 'linked_to' test for MacOS

testinfra/modules/service.py
After deploying some new service overrides I realised I'd made a spelling mistake in one of the fields, this should catch these by asserting there's no warnings.
I've tested these manually on a linux box, should be simple for you to do, just add a junk field to the unit file and it should now fail.
Open to name changes on `is_valid`, it seemed most in keeping with the package names.  Unsure where to add docs as well?
=> Feature: Add is_valid method to systemd.

doc/source/examples.rst
I don't often see very verbose outputs to nrpe checks, so I would recommend using --tb none for that. (The operator can then go and run the test manually to get more information)
=> [docs] Update --nagios documentation to remove tracebacks

doc/source/backends.rst
Among the changes, I removed the references to ` --sudo` for the various backends because that option is already documented at the beginning of the page.
=> Fix typos and style for backends.rst

doc/source/examples.rst
I was experimenting with the docker examples and noticed that there appeared to be typo - it looks like subprocess.check_all(...) should actually be subprocess.check_call(...)
=> Change check_all to check_call in doc example

testinfra/backend/paramiko.py
The following configuration parameters will allow for GSSAPI authentication using the paramiko backend if properly configured inside the ssh_config file.
Additional package requirement : python-gssapi
=> Add support for GSSAPI in Paramiko Backend.

testinfra/backend/winrm.py
Hello,
It seems there is a typo in the WinRM backend that prevents it to connect to WinRM services over HTTPS.
This change fixed the issue against our environment.
Remote host: AWS Windows server 2016 base 10, version 2018.03.24
Testinfra host: Ubuntu Linux 16.04, python 3.6
Example PowerShell script to configure WinRM service with HTTPS:  https://github.com/PeteGoo/packer-win-aws/blob/master/ec2-userdata.ps1
=> Use HTTPS protocol when specified in WinRM backend

testinfra/modules/socket.py
They are reported as 'UNCONN' in 'ss -l -u -n' output.
Closes #311
=> Socket: fix detection of udp listening sockets

testinfra/plugin.py
It appears that a change in ansible 2.5.1 caused hosts in the inventory
to be returned in a non-deterministic order. When using testinfra with
pytest-xdist, that can result in a failure during test collection:
"Different tests were collected between gwX and gwY"
Simply sorting our hosts fixes this issue.
Example of the failure:
```
$ cat test.py
#!/usr/bin/env python
testinfra_hosts = ['!group_b']
class TestXdist(object):
def test_one(self, host):
assert True
def test_two(self, host):
assert True
def test_three(self, host):
assert True
$ cat inventory/test
[group_a]
host_a_0
[group_b]
host_b_0
[group_c]
host_c_0
[group_d]
host_d_0
[group_e]
host_e_0
$ py.test -v -n auto --connection=ansible --ansible-inventory=./inventory ./test.py
============================================== test …
```
=> Fix test generation with ansible and xdist

test/test_modules.py, testinfra/modules/package.py
Also add a test and avoid shell injections when running 'dpkg-query'
Closes #321
=> Package: fix is_installed for non-installed packages on Debian

test/test_modules.py, testinfra/modules/package.py
On Debian based systems, dpkg-query might exit with a return code 0 for
uninstalled packages (in case of previously installed packages). In this
case raise an AssertionError instead of returning None
Closes #325
=> Package: fix version() behavior for uninstalled packages

test/test_modules.py, testinfra/modules/file.py
Implements \_\_eq\_\_ and \_\_ne\_\_ methods on the File object.
If both objects are files, the paths are getting compared,
if the other object is a string, it's compared with the path directly.
=> fix issue #303

CHANGELOG.rst, images/centos_6/Dockerfile, test/conftest.py, test/test_modules.py, testinfra/backend/ansible.py, testinfra/modules/file.py, testinfra/modules/package.py, testinfra/modules/service.py, testinfra/utils/ansible_runner.py, tox.ini
Presently, the caching applied to `AnsibleRunners` is only effective at
the host level -- meaning that while we'll only check the inventory once
per host, we cannot do it less often. With dynamic inventories that can
take multiple seconds to compute their value, this cost can become
expensive quickly.
This change moves the cache to the class level, so that we'll execute
the ansible inventory once per `ansible_inventory` argument and no more
often.
NB: if a client calls into AnsibleBackend using a relative path, changes
the working directory, and calls `get_hosts` again with the same
relative path, they'll get stale results.
That workflow seems unlikely, but it might be nice to at least log a message on cache hit so we can shorten the time to resolution in that situation – I haven't been …
=> Share runners (and parsed inventory) among hosts

doc/source/backends.rst, images/centos_6/Dockerfile, test/conftest.py, test/test_backends.py, test/test_modules.py, testinfra/backend/__init__.py, testinfra/backend/ansible.py, testinfra/backend/base.py, testinfra/backend/kubectl.py, testinfra/modules/service.py, testinfra/utils/ansible_runner.py, tox.ini
usage: py.test --connection=kubectl --hosts=<pod-name>[/<image-name>][%<namespace>] ...
where namespace is the k8s namespace where you work inside.
So it's not necassary to switch the default namespace from your kubectl client installation
to access/work with a specific namespace
=> Add namespace support for kubectl connector.

testinfra/plugin.py
This issue has been introduced in 1.13.1 by febe2cc hosts and ids where
not sorted in a same way, this result in having a wrong "pytest_id"
displayed.
Closes #347
=> Fix multi-host test ordering

testinfra/backend/__init__.py
I've noticed that testinfra always attempts to use HTTPS with the WinRM backend, even when I set the `no_ssl` query parameter. This is causing problems for me because the host in question is not configured to support HTTPS.
It looks like this bug was probably introduced when the `ssl` and `verify_ssl` parameters got inverted--when their names changed, the new names were not added to the 'whitelist' of accepted query parameters on line 51 of `testinfra/backend/__init__.py`.
Adding `no_ssl` and `no_verify_ssl` to the list allows these query parameters to propagate to the WinRMBackend.
=> Use HTTP with WinRM when user disables SSL

testinfra/modules/iptables.py
host.iptables().get_rules('table', 'CHAIN') is wrong and it should be host.iptables.rules('table', 'CHAIN')
=> Fix iptables doc example

test/conftest.py
Silence the warning:
RemovedInPytest4Warning: MarkInfo objects are deprecated as they
contain merged marks which are hard to deal with correctly.
by seeing if metafunc.definition is defined, and if so using the
get_closest_marker() function instead.  This should maintain forward
and backwards compatability as required.
=> Work around MarkInfo object warnings

test/test_modules.py, testinfra/modules/iptables.py
Add basic ip6tables support to iptables module.  Adds a "version"
argument to the existing module which switches it to use the ip6tables
binary.
=> Add ip6tables support to iptables module

testinfra/modules/sysctl.py
When /sbin is not in PATH, the sysctl module fails to run.
Closes #376
=> sysctl: find sysctl outside of PATH (/sbin)

test/test_modules.py, testinfra/backend/base.py
Add a simple `succeeded/failed` interface which allows for simpler assertion in tests.
It is more readable to have tests like:
```python
assert host.run("false").failed
assert host.run("true").succeeded
```
Instead of:
```python
assert host.run("false").rc != 0
assert host.run("true").rc == 0
```
=> Improve CommandResult interface

test/test_modules.py, testinfra/modules/ansible.py, testinfra/utils/ansible_runner.py
Adds support for setting `become` when running an Ansible module:
```py
host.ansible('service', 'name=docker-compose state=restarted', check=False, become=True)
```
The  `sudo()` context manger does not work for Ansible modules; calls to `host.ansible()` are passed to `AnsibleRunner.run()` without going through `get_command` (which is what [`sudo()` monkey patches `get_sudo_command`](https://github.com/philpep/testinfra/blob/master/testinfra/modules/sudo.py#L48) in as). See `test_ansible_module_become` test for evidence of this.
=> add support for setting 'become' when running Ansible module

doc/source/backends.rst, testinfra/backend/__init__.py, testinfra/backend/winrm.py
Add ability to pass timeouts to the winrm backend
The default read and operation timeouts in pywinrm are quite
low - 30 and 20 respectively.
Windows machines in common configurations frequently will exceed these
timeouts on initial login.  I'm frequently finding the first of a suite
of tests using the winrm backend against newly built machines would
fail but the rest would succeed.  Increasing the read and operation timeout parameters used by pywinrm fixed the issue.
I'm guessing others have encountered this issue - ansible had an
identical issue filed which is fixed by the same method: ansible/ansible#16873
This change allows specifying these parameters as query parameters
in the host spec.
=> Add ability to pass timeouts to the winrm backend

testinfra/plugin.py
Hi,
When an error occurs, testinfra generates a lot of messages. With stderr and logging capture, the messages appears _twice_. This floods the screen of user. So here is a contribution to start the discussion.
The idea is to avoid `basicConfig` which configures output to stderr.
However, not configuring logging can trigger warning if a message does not have a handler. Thus, i added a check and ensure that root logger have at least a NullHandler. Actually, pytest adds a CapLog handler.
This pattern is common in library using logging to avoid requiring logging configuration. Using NullHandler allows app to call basicConfig on its own or any other configuration.
What do you think of this ?
Regards,
Étienne
Note: I executed `tox -e py35 -- -k ansible` locally before opening this PR.
``` …
```
=> Avoid configuring logging

test/test_backends.py, testinfra/backend/base.py, testinfra/utils/__init__.py
When host, user or password contains specials characters in url string,
we expect them to be urlencoded and we should decode them back.
Closes #387
=> Unquote host, user and password in host url spec

testinfra/plugin.py
Use warnings from python instead.
Closes #394
=> Fix pytest config.warn which has been dropped since pytest 4

doc/source/modules.rst
Adding Docker `autoclass` to `modules.rst` for the new Docker Module #300
=> add `module.docker.Docker` class to docs

testinfra/modules/service.py
Systemd might not be the pid 1 on docker hosts for instance.
Seems "is-enabled" works but not "is-active", in this case (observed on
ubuntu:xenial) the exit code is 1 with message "Failed to connect to
bus: No such file or directory".
Closes #418
=> service: systemd fallback to sysv when systemctl is not working

pylintrc, testinfra/modules/package.py, testinfra/modules/systeminfo.py, testinfra/modules/user.py
This adds some basic support for Windows packages (chocolatey) and users. I'm not sure how to add tests for this because the Windows docker images that are available require a Windows host to run.  Also, I apologize for this in advance. We needed to be able to test some things at work, so I thought I'd see if I could add some very basic Windows support. This helps to start addressing #330, but I haven't yet worked out a solution for the file module.
=> Add Windows support

test/conftest.py
Followup f29de6f, we do not support ansible v1 anymore.
Also require ansible to be installed in tests, never skip them.
=> Drop ansible v1 handling in tests

images/debian_stretch/Dockerfile
systemd requires the "container" variable be set when it is running
inside a container [1].  Without this, on some hosts the container can
go into a silent purgatory enforced by selinux where systemd is
running, but sshd or other services never start in the container
... leading to ansible tests simply hanging forever trying to ssh in.
[1] https://www.freedesktop.org/wiki/Software/systemd/ContainerInterface/
=> Add container env to debian Stretch Dockerfile

pylintrc, test/test_backends.py, testinfra/backend/ansible.py, testinfra/utils/__init__.py, testinfra/utils/ansible_runner.py
Implementation for https://github.com/philpep/testinfra/issues/431
=> New ansible runner

test/test_backends.py, testinfra/backend/base.py, testinfra/utils/__init__.py, testinfra/utils/ansible_runner.py
An ansible inventory might specify the "ansible_host" as a literal
ipv6 address.
This needs handling in ingestion; in ansible_runner.py we add a check
if the host looks like a literal ipv6 address and enclose it in []'s
per RFC2732 (a util function is added for this, which works better on
Python 3).
When connecting, testinfra's host parsing in backend/base.py then
needs to check for []'s in the connection string and extract the
literal ipv6 address if found.  The test-case for this is updated with
a few ipv6 examples.
=> Handle literal ipv6 addresses

test/test_backends.py, testinfra/backend/ansible.py, testinfra/utils/ansible_runner.py
When host list is not specified we should parametrize "all" ansible hosts.
Closes #437
=> ansible: fix when host list is not specified

testinfra/backend/paramiko.py
cfg does not contain RequestTTY item, so with lines sudo can`t get tty
=> Fix sudo for paramiko backend

test/test_backends.py, test/test_modules.py, testinfra/utils/ansible_runner.py
This key was returned by ansible python API in testinfra 2.X and users
rely on it.
Closes #443
=> ansible: add "groups" key to get_variables()

test/test_backends.py, testinfra/utils/ansible_runner.py
Hi there, we received a report on https://github.com/ansible/molecule/issues/2069 about Molecule failing to make an SSH connection and after a quick glance over in https://github.com/ansible/molecule/issues/2069#issuecomment-496456638, I think I have a patch.
The short of it is, Ansible advertises that you can use both "ansible_ssh_private_key_file" and "ansible_private_key_file" for specifying SSH connection options and Molecule happens to use the "ansible_private_key_file" by default. The new Ansible runner implementation here in Testinfra (from what I can tell) does not pick this up.
Didn't dig too deeply on this but hopefully this goes in the right direction ...
=> Support `ansible_private_key_file` as well

testinfra/utils/ansible_runner.py
Avoids Ansible bug https://github.com/ansible/ansible/issues/59973 which
prevents testinfra from parsing inventory by disabling ansible verbosity.
Fixes: #470
=> Avoid JSON parsing error in get_ansible_inventory

testinfra/backend/base.py
For those using Ansible inventories and who want to log in their `pytest`'s with `INFO` logging, this currently will log sensitive vault variables. It'd be preferable if this was just a `DEBUG` log instead.
This is the only `INFO` log I encounter in `testinfra` when using an `ansible` connection so hopefully this won't upset anyone. Thanks for a great plugin!
=> DEBUG log when running commands

test/test_modules.py
For some reason ssh may be slow to start and "is_running" is returning
False. Wait at max 10 seconds for ssh to be running.
=> Fix flapping test_ssh_service for alpine and archlinux

doc/source/backends.rst, test/test_backends.py, testinfra/backend/__init__.py, testinfra/backend/ansible.py, testinfra/utils/ansible_runner.py
Since testinfra 3.X we use our own implementation for local, paramiko,
ssh and docker connections for ansible hosts (by parsing the inventory
to get connections details).
This break other connections handled by ansible which where handled in
testinfra 2.X.
Add a force_ansible (default False) parameter to the ansible backend.
When force_ansible is set to True, testinfra will call ansible for all
remote command.
When ansible inventory parsing detect an unhandled connection type (for
example "network_cli"), it will call ansible for all remote commands as
well.
Add tests by adding a new host with "force_ansible=True" in existing
backend tests. Also expand HOSTS, SUDO_HOSTS etc, this is less "DRY" but
more explicit.
There's a known encoding issue with ansible (it was already present in …
=> ansible: allow to use ansible for all commands with force_ansible=True.

test/test_backends.py, testinfra/backend/ssh.py
safe-ssh already use a lot of redirection and was expecting the input
command was a single command with arguments.
When testing with more complex commands, the code may crash.
Avoid this by wrapping the command in a "sh -c" execution.
Add a sanity check for "host.run()" testing exit code, stdout and stderr
are decoded correctly for all tested backends (ssh, safe-ssh, paramiko,
ansible, ansible with force_ansible etc).
=> Fix safe-ssh backend with shell redirections

test/test_backends.py, testinfra/utils/ansible_runner.py
When ANSIBLE_ANY_ERRORS_FATAL is set to True (this can be set from
environment, and probably from inventory or ansible configuration
files), the ansible call exit with status 8 when running a command that
fail to run.
Detail of exit codes can be found here:
https://github.com/ansible/ansible/blob/523e40e993c06a6c15234c9a3c951b5398e44184/lib/ansible/executor/task_queue_manager.py#L63-L68
Add `8` to the expected exit codes and add a non regression test.
Closes #481
=> Fix pure ansible connections with ANSIBLE_ANY_ERRORS_FATAL=True

test/test_modules.py
The test still random fail for unknown reasons...
=> Fix flapping test_ssh_service for archlinux

testinfra/modules/__init__.py, testinfra/modules/blockdevice.py
I found I need some block device info for my tests, and testinfra got no such module, so I wrote it.
It is a wrapper over `blockdev --report` with some logic on top.
Gathered information:
* size
* r/w or r/o status
* sector_size
* block_size
* partition or not
* read ahead value
* basic sanity check (`is_block_device`)
=> Add BlockDevice module to query block device info.

test/test_backends.py, testinfra/utils/ansible_runner.py
When inventory is empty or an unexistent file, ansible-inventory will
not raise an error but just a warning:
% ansible-inventory --list -i /doesnotexists
[WARNING]: Unable to parse /doesnotexists as an inventory source
[WARNING]: No inventory was parsed, only implicit localhost is
available
{
"_meta": {
"hostvars": {}
},
"all": {
"children": [
"ungrouped"
]
},
"ungrouped": {}
}
% echo $?
0
Raise an error when inventory is empty and host is not explicitly set to
localhost.
This mean:
python -m pytest --ansible-inventory /doesnotexists --connection ansible => RAISE
python -m pytest --ansible-inventory /doesnotexists --connection ansible --hosts all => RAISE
python -m pytest --ansible-inventory /doesnotexists --connection ansible --hosts 'local*' => RAISE
python -m pytest --ansible-inventory …
=> ansible: raise an error in case of empty inventory

test/test_backends.py, testinfra/backend/ssh.py
% sign need to be escaped from format string.
Also avoid double ControlMaster/ControlPersist/ConnectTimeout in ssh command.
Closes #486
=> ansible: fix ansible ssh args escaping

doc/source/backends.rst, test/test_backends.py, testinfra/backend/ssh.py, testinfra/utils/ansible_runner.py
If ssh identity file is not provided via `--ssh-identity-file` flag, testinfra will try 
to use `ansible_ssh_private_key_file`, `ansible_private_key_file` and, finally, 
`ansible_user` with `ansible_ssh_pass` variables, both should be specified.
=> ansible + ssh backend: support for passwords via sshpass

testinfra/plugin.py
Inspired from https://github.com/yashtodi94/pytest-custom_exit_code
This should fix tests failing with pytest 5 due to "sys.exit()" raising
weird behaviors in pytest.
Tested with pytest 5.X, 4.X and 3.X series.
=> Use pytest way of controlling exit status

doc/source/backends.rst, setup.cfg
This adds environment selectors for backends in setup.cfg.  The
inspiration here is that the ansible backend actually requires
paramiko but it isn't specified anywhere.  Having environment markers
makes it a bit eaiser in CI environments to ensure everything is
present.
I've taken a guess at the requirements for the others; although
they're simple I think it's good for consistency to have all backends
with their own environment.  A documentation note is added too.
=> Add extras for backend dependencies

test/test_backends.py, test/test_modules.py, testinfra/modules/ansible.py, testinfra/utils/ansible_runner.py
Instead of adding a keyword argument for each supported option, allow users to pass arguments directly to the ansible command line.
Support for passing [extra vars](https://docs.ansible.com/ansible/latest/cli/ansible.html#cmdoption-ansible-e) has been proposed in https://github.com/philpep/testinfra/pull/462.
This approach offers support for extra vars, as well as become user, verbosity, running in diff mode, etc.
=> Allow specifying arguments to the Ansible CLI

pylintrc, test/test_modules.py, testinfra/modules/file.py
So that users can assert on items in a directory. Just like the [File.content](https://github.com/philpep/testinfra/blob/02a9338b1e8eef7da8737099ee1445341e454fe1/testinfra/modules/file.py#L141) which is useful to assert if a file content contains a certain value, but for directory items.
=> Implement File.list_dir to list items in a directory

images/debian_stretch/Dockerfile
if LC_* is not `fr_FR.ISO-8859-15` on the system running pytest
from recent master (fc8a824d0f95a672091560f76a5b91e65f1cd6d2), running the test suite from a Linux computer with LC_* environment variables set to `en_US.UTF-8` produces errors for `test_encoding`. 
My locales :
```
LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
```
Full pytest log is attached : 
[test_encoding_fail.txt](https://github.com/philpep/testinfra/files/4227890/test_encoding_fail.txt)
=> fix test_encoding failing for ansible backend

test/test_modules.py, testinfra/modules/file.py
This documented as a method in 4.1 changelog and it seems more intuitive
this way as it clearly indicates that a computation is performed.
=> Make File.listdir a method

testinfra/utils/ansible_runner.py
Currently `get_ansible_host()` ignores remote_user and remote_port variables from ansible.cfg. This means that if you're using non-default ssh port or if your local username is different from the remote username, you have to set ansible_port or ansible_user variables in your ansible inventory, which is often inconvenient, especially when you're using shared inventory file.
=> Respect remote_user and remote_port in ansible.cfg

test/test_modules.py, testinfra/modules/systeminfo.py
This allows you to switch on the host architecture easily.  "uname -m"
seems to be globally acceptable on unix-y hosts, Windows has
%PROCESSOR_ARCHITECTURE%.
=> Add architecture to sysinfo

images/centos_6/Dockerfile, test/test_modules.py, testinfra/modules/iptables.py
If multiple tests are executed in parallel (e.g. via pytest-xdist) and
more than one test queries the iptables rules on the same host
simultaneously, the following error will occur:
E       AssertionError: Unexpected exit code 4 for
CommandResult(command='iptables -t filter -S', exit_status=4,
stdout='', stderr='Another app is currently holding the xtables
lock. Perhaps you want to use the -w option?')
Iptables has an internal lock to prevent multiple simultaneous
invocations.  This change implements that suggestion and adds "-w 90" to
the iptables command so that we will wait up to 90 seconds to obtain the
lock.
Unfortunatelly centos 6 is still maintained but doesn't have support for
iptables with "-w" argument. So we have handle this by trying iptables
with "-w 90", if it fail we retry …
=> Add '-w' argument to iptables

test/test_modules.py, testinfra/modules/service.py
Hi
I'm sorry but I introduced a bug with my PR #568. The `systemcl is-enabled` command doesn't return 0 when the service is not enabled. So my check `cmd.rc == 0` was not relevant in this case.
Sorry for this bug. I add on test to check if my code is valid. This time, it should be ok !
=> Fix is_masked method on systemd service 

setup.cfg
As part of migrating the project under pytest-dev organization, we need to rename the package and repository name. The installed python module remains testinfra.
pypi and testpypi have already being bootstrapped with `5.3.2a0` release in order to create the project. See https://pypi.org/project/pytest-testinfra/
Related: https://github.com/philpep/testinfra/issues/484
Related: https://github.com/pytest-dev/meta/issues/1
=> Rename project to pytest-infra

test/test_invocation.py
Allow to execute invocation tests from sources, without `testinfra` being installed, using for example:
PYTHONPATH=. pytest test/test_invocation.py
Fix this error reported by @lyknode on [`#testinfra`](https://webchat.freenode.net/#bip) IRC channel:
=============================== FAILURES ===============================
__________________________ test_nagios_notest __________________________
testdir = <Testdir local('/tmp/pytest-of-pilou/pytest/test_nagios_notest0')>
def test_nagios_notest(testdir):
result = testdir.runpytest('--nagios', '-q', '--tb=no')
>       assert result.ret == 0
E       assert 4 == 0
E        +  where 4 = <RunResult ret=4 len(stdout.lines)=1 len(stderr.lines)=6 duration=0.06s>.ret
src/testinfra/test/test_invocation.py:18: AssertionError
------------------------- …
=> Allow to run invocation tests without testinfra installed

testinfra/plugin.py
Fix this exception:
python3 -c "import sys; from testinfra.plugin import SpooledTemporaryFile;\
SpooledTemporaryFile(encoding=sys.stdout.encoding).fileno()"
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/usr/lib/python3.8/tempfile.py", line 839, in fileno
self.rollover()
File "/usr/lib/python3.8/tempfile.py", line 793, in rollover
newfile = self._file = TemporaryFile(**self._TemporaryFileArgs)
File "/usr/lib/python3.8/tempfile.py", line 744, in TemporaryFile
return _io.open(fd, mode, buffering=buffering,
ValueError: binary mode doesn't take an encoding argument
=> Remove "encoding" parameter when binary mode is used

testinfra/backend/paramiko.py
Authorization with username and password is now possible.
The password attribute will now get passed to Paramiko. 
As I noticed it just seems to be a missing configuration value.
Users can now authenticate using connection strings like the following one:
```python
testinfra.get_host(F"paramiko://{username}:{password}@{address}:{port}")
```
=> Add support for password based authorization with paramiko

setup.cfg
3.5 is EOL and our code use f-strings.
=> require python >= 3.6

testinfra/utils/ansible_runner.py
If `ssh_args` is set in Ansible's configuration file, use those arguments when
connecting to hosts.
Signed-off-by: Benoît Knecht <bknecht@protonmail.ch>
=> utils/ansible_runner: Use ssh_args from ansible.cfg

testinfra/modules/service.py
I couldn't quite get the unit tests working. I'll leave that to Travis. The change is designed to not break anything :-)
=> service-module: use /run/systemd/system/ to detect systemd (fixes #546)

test/test_backends.py, testinfra/backend/__init__.py
If a host appears multiple times in host specs (which can typically happen if a
host is a member of multiple Ansible groups for instance), testinfra would run
tests on that host multiple times.
This commit turns the list of hosts that are being considered into a set, and
makes each one of them hashable in such a way that two hosts are considered
equal if they have the same name, connection parameters, etc.
As a result, if a host finds itself listed multiple times with the same backend
and connection parameters, testinfra will run the tests on that host only once.
Signed-off-by: Benoît Knecht <bknecht@protonmail.ch>
=> backend: Deduplicate hosts returned by get_backends()

test/test_modules.py, testinfra/modules/package.py
A CentOS system with dpkg package installed fails for all packages
is_installed checks. This happens because the decision to use the module class
is based on the presence of `dpkg-query` binary.
This commit changes the check to look for `system_info.distribution`, and
makes CentOS 6 distribution name lower case to be consistent.
=> Fix module class for RPM and Debian distributions #570

testinfra/backend/base.py
The quote() function used to live in pipes module in python2 and, while
an import exists in pipes for backwards compatibility, it seems better
to import from shlex.
=> Import quote() from shlex

tox.ini
As of
https://www.python.org/dev/peps/pep-0478/
Python 3.5 has reached end-of-life. Removing it from the test environments to reflect this state.
=> Removing Test Python 3.5 Environment

testinfra/modules/file.py
Hello,
Fix #594 a small issue in the `File.mode` documentation, see my [comment][1] in the issue for more detail.
Best.
[1]: https://github.com/pytest-dev/pytest-testinfra/issues/594#issuecomment-750370503
=> Fix #594: mode documentation

testinfra/modules/blockdevice.py
There is a small typo in testinfra/modules/blockdevice.py.
Should read `underlying` rather than `underlaying`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: fix simple typo, underlaying -> underlying

testinfra/modules/systeminfo.py, tox.ini
This PR is to fix issue #590. It includes the platform module to resolve the OS type correctly. This enables tests running against `WinRM` to behave correctly if a MSYS2 is installed on the windows system.
It was tested against the current test suite.
Resolves: #590
=> Fix #590: Systeminfo doesn't resolve Windows correctly 

test/conftest.py, test/test_modules.py, testinfra/host.py, tox.ini
Developers using WSL2 (Windows Subsystem for Linux) face the problem
that there is currently no systemd support. For the test `test_iptables`
a service is started and it fails on WSL2 hosts.
This commit introduces a pytest marker to skip the test if the host is
executing on WSL2.
With the skipped test the output of the tox run is
```bash
test/test_modules.py::test_iptables[docker://debian_buster]
[gw1] [ 94%] SKIPPED test/test_modules.py::test_iptables[docker://debian_buster]
180 passed, 1 skipped in 100.36s (0:01:40)
```
=> fix(tests): adding WSL2 support

test/test_modules.py, testinfra/modules/addr.py
Hello,
Here is a try to resolve #559 by supporting network namespaces in the `addr` module.
It's not easy to test since it requires privileged mode in docker and it's not possible (as far as I know) to setup a namespace in a Docker image at build time. So I have only made some minimal test.
I'm not sure of the way to handle the case when `ip` command is not available. The current implementation throws immediately a `NotImplementedError` in this case.
Note: In some cases I've used the `format` method to format string since I had trouble using the classic `%` way. I don't know if it's a problem or if we need to stick to one convention.
Best.
=> First implementation of network namespaces in addr module

test/test_modules.py, testinfra/modules/pip.py
Hello,
This PR adds [`pip check`](https://pip.pypa.io/en/stable/reference/pip_check/) support in `PipPackage` module.
> Verify installed packages have compatible dependencies.
Best
=> pip check support in PipPackage module

doc/source/modules.rst, test/test_modules.py, testinfra/modules/__init__.py, testinfra/modules/pip.py
Hello,
As discussed in #605 rename `pip_package` to `pip` and make it works like `package` module e.g:
```python
django = pip('Django')
assert django.is_installed
assert django.version.startswith('3.1')
assert pip.check()
```
First implementation of `is_installed` and `version` as properties.
So `Pip` is now a `Module` instead of `InstanceModule` and API not related to a package are implemented as a `classmethod`.
`pip_package` is deprecated with a proper warning (in the code and in the doc) and still works as before.
_shell escaped_ every `pip` calls as suggested by @philpep.
Best
=> pip refactoring: implementation of installed and version

testinfra/plugin.py
Use getoption method to handle the case when the options aren't
set and use default value of 0 for verbose.
Fixes #451
=> Fix option retrieval.

Makefile, testinfra/modules/docker.py
Hello,
Implemented a way to get Docker version.
```python
host.docker.client_version()
host.docker.server_version()
host.docker.version()
host.docker.version("{{.Client.Context}}")
```
**Notes**
- It's [possible in Python `3.9`][1] to combine `@classmethod` and `@property` to get something like that `host.docker.client_version`.
- Are you interested in having an optional `parse` flag implementing [`packaging.version.parse`][2] ? 
```python
from packaging import version
version.parse("2.3.1") < version.parse("10.1.2")
assert host.docker.server_version(parse=True) > version.parse("19.03")
```
I've added the ability to run a local HTTP server through the `make` in order to check the generated doc locally.
```bash
make doc serve
```
Best
[1]: https://stackoverflow.com/a/64738850/4413446
[2]: …
=> Docker version

test-requirements.txt, test/test_modules.py, testinfra/modules/interface.py, tox.ini
Hello,
First try to resolve #613.
@rgarrigue not sure if it matches your expectations.
```python
host.interface.names()
default_itf = host.interface.default()
default_itf.name
default_itf.addresses
```
It's a work in progress. Open to suggestions and improvements either in the naming and in the implementation.
Best
=> Interface names and default

test/test_modules.py, testinfra/modules/interface.py, testinfra/modules/socket.py
Fix Issue [#616 AttributeError: 'LinuxInterface' object has no attribute 'adresses'](https://github.com/pytest-dev/pytest-testinfra/issues/616)
=> Rename adresses to addresses

testinfra/backend/salt.py
Use of expr_form is depricated and no longer works in the latest salt client version.
=> expr_form is depricated in salt backend client, replaced with tgt_type

dev-requirements.txt, test/test_modules.py, tox.ini
Two tiny changes to make the CI green again:
- bump release of the test package in the Alpine image
- force a more recent version of the hacking plugin
=> Fix the CI

testinfra/modules/package.py
On Fedora you can also install dpkg, which will cause testinfra to think that
the package manager is actually DPKG and not RPM. Thus we instead use the
system_info.distribution value to prefer rpm on Fedora
=> Use RpmPackage on CentOS and Fedora and not only on CentOS

testinfra/host.py, testinfra/modules/file.py
Testinfra uses `readlink -f` and `command -v` which are both not supported by older versions of busybox. However this can be worked around by using `realpath` and `which`, respectively.
=> Support older busybox

doc/source/modules.rst
Displays the already existing module `blockdevice` in the documentation.
=> Display blockdevice in module documentation

testinfra/utils/ansible_runner.py
As an extension of #627, this commit adds the ability to get
`ansible_ssh_common_args` and `ansible_ssh_extra_args` from the configuration
file or environment variables, with the expected precedence:
| Configuration File                      | Host Variable             | Environment               |
| --------------------------------------- | ------------------------- | ------------------------- |
| `[ssh_connection]`<br>`ssh_common_args` | `ansible_ssh_common_args` | `ANSIBLE_SSH_COMMON_ARGS` |
| `[ssh_connection]`<br>`ssh_extra_args`  | `ansible_ssh_extra_args`  | `ANSIBLE_SSH_EXTRA_ARGS`  |
Signed-off-by: Benoît Knecht <bknecht@protonmail.ch>
=> ansible: Support SSH args from environment

testinfra/host.py
Commit "Fallback to which when command -v fails" has changed things to call which(1) in find_command
but used "self.path" has argument to which(1), leading to:
E       AttributeError: 'Host' object has no attribute 'path'
Update the call to pass "command" as argument.
Signed-off-by: Arnaud Patard <apatard@hupstream.com>
=> host.py: Fix "which" fallback in find_command

doc/source/backends.rst
This adds documentation to a number of useful Ansible configuration options:
* `--ansible-inventory`
* `--ssh-config`
and environment variables:
* `ANSIBLE_REMOTE_USER`
* `ANSIBLE_SSH_EXTRA_ARGS`
* `ANSIBLE_SSH_COMMON_ARGS`
* `ANSIBLE_REMOTE_PORT`
* `ANSIBLE_BECOME_USER`
* `ANSIBLE_BECOME`
=> Update Ansible docs

doc/source/backends.rst, testinfra/plugin.py
This is follow up to https://github.com/pytest-dev/pytest-testinfra/commit/b749619fbd28a90c3e323fa66b2329aff60facf4 and seems related to https://github.com/pytest-dev/pytest-testinfra/issues/467 but does not solve it:
Expose the ssh_extra_options as a pytest CLI option. This is already accepted as a kwarg to the ssh backend. My use-case was to disable SSH host key checking, I was able to work-around it via a configfile but this seemed like a nice feeature to expose up as its own option, and comments in #467 seem to indicate this was the intent.
=> add ssh_extra_args option

test/test_backends.py, testinfra/utils/ansible_runner.py
Molecule's Docker driver sets `ansible_connection` to
`community.docker.docker`, making
`testinfra.utils.ansible_runner.AnsibleRunner.get_host` fail to return
such a host in a Molecule test using the Docker driver.
Fix this by translating "community.docker.docker" to "docker".
Closes #648.
=> Handle ansible_connection type community.docker.docker

testinfra/modules/package.py
Why treat manjarolinux <=> arch different than 
e.g. debian <=> ubuntu 
or fedora <=>  centos
==> 
Add support for ManjaroLinux via detection of distribution
=> Add support for Manjaro-Linux, really closes #503

testinfra/plugin.py
Pytest has deprecated markers for hooks configuration. See: https://docs.pytest.org/en/latest/deprecations.html#configuring-hook-specs-impls-using-markers
Each envocation of pytest with python warning enabled would produce the following message:
PytestDeprecationWarning: The hookimpl pytest_configure uses old-style configuration options (marks or attributes).
Please use the pytest.hookimpl(trylast=True) decorator instead
This commit fixes that issue.
=> Remove PytestDeprecationWarning about config opts

testinfra/modules/file.py
When using this today, I struggled to find how this works in the documentation. This hopefully gives some pointers for people how to structure their pattern. I wanted to find out how to search for "term1" or "term2" which in gnu grep (or extended grep in other grep versions) would be "term1\|term2" but didn't include this as this depends too much on the grep used. Feel free to change or ask for improvements. Not fully satisfied yet and did this via web so not sure if flake8 is happy.
=> Add basic docu for file.contains

.pre-commit-config.yaml
Running tox results in an error message:
> Configuration is invalid:
>        - [extras.pipfile_deprecated_finder.2] \
>          'pip-shims<=0.3.4' does not match '^[a-zA-Z-_.0-9]+$'
This is caused by additional checks in poetry-core >= 1.5.0 and fixed fixed by https://github.com/PyCQA/isort/pull/2078
=> pre-commit: update isort to 5.12.0 to silence import error

testinfra/modules/interface.py
Returns the routes associated with the interface, optionally filtered by scope (`host`, `link` or `global`).
=> modules/interface: Add routes() function

test/conftest.py
As described in https://github.com/moby/moby/issues/42442, docker daemon starts to expose a container port on different host ports for IPv4 and IPv6 which breaks the ssh/safe-ssh/ansible backend tests for some containers.
To prevent this behavior and flaky tests, only the first line from the `docker port %s 22` command gets parsed to acquire the mapped SSH port.
=> Workaround Docker#42442 by using IPv4 SSH only

test/test_modules.py, testinfra/modules/file.py, testinfra/modules/process.py
Links to Busybox can be hardlinks as well, an example is the [Prometheus node exporter Helm chart](https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-node-exporter). `get_module_class` is not sufficient in this case.
Therefore, to identify a hardlink, property `inode` is implemented as a GNUFile property. The added condition compares Inodes of `/bin/ps` and `/bin/busybox` as well as the simple existance of busybox itself. Some testcases for the hardlink check via `inode` property were created in `test/test_modules.py`.
=> Conditional Check Hardlink to Busybox Binary

test/test_modules.py, testinfra/modules/file.py
Hi,
this PR contains `File.is_executable` and some additional docstrings.
This simplified the check if a script/program is executable
```
f = host.file('/path/to/myscript')
assert f.is_executable
```
instead of
```
f = host.file('/path/to/myscript')
assert f.exists and f.mode == 0o700
```
Regards,
Carsten
=> Add File.is_executable

testinfra/modules/group.py
a group name "None" will cause unexpected results, as all functions need the group name.
=> Make group name mandatory

setup.cfg
to prevent deprecation warning.
Please check next builds that the license file is always included as the new metadata works only for wheels - not sdists.
=> Use new key to specify license file in setup.cfg

testinfra/modules/package.py, testinfra/modules/systeminfo.py
openSUSE distributions can have rpm, dnf and dpkg installed at the same time, but the system is always maintained via rpm. so explicitly detect it as such. Also don't trust lsb-release too much, /etc/os-release is the preferred method so pick that one first.
=> Improve system detection for openSUSE style distributions

testinfra/utils/ansible_runner.py
`cmp` is already a string. Therefore, the `join()` instruction is not necessary and only inserts additional spaces.
=> Fix output of error message

test/test_backends.py, test/test_modules.py, testinfra/utils/ansible_runner.py
The Ansible variable group names contains all groups the host is part of and not only the direct parent groups, this is a fix to reflect how ansible works.
Link to documentation:
- https://docs.ansible.com/ansible/latest/reference_appendices/special_variables.html#term-group_names
=> Ansible: Fix for missing group names in get_variables()

testinfra/modules/blockdevice.py
The `blockdevice` module raises a `RuntimeError` if `blockdev` returns with a non-zero exit code, or if stderr is not empty.
But the latter can happen even when there's no failure at all, for instance if `sshd` has a banner message configured (which gets output to stderr whenever someone connects to the host).
=> testinfra/modules/blockdevice: Don't fail on stderr

testinfra/modules/service.py
The old implementation limits the usage of SystemdService.is_valid() to `.service` units. This implementation allows checking all types of unit files with `is_valid()` (`systemd-analyze verify <unitname.suffix>`).
=> Extend list of valid suffixes for systemd units

doc/source/modules.rst, testinfra/modules/environment.py
=> Add missing Environment doc section

testinfra/backend/ansible.py, testinfra/backend/base.py, testinfra/backend/salt.py, testinfra/backend/winrm.py
Following discussion for #717, make `CommandResult` a dataclass.
=> Make CommandResult a dataclass

setup.cfg, testinfra/plugin.py
Makes testinfra v10.0.0 work with Python 3.9 and pytest 6.2.2, which is being used in CentOS-Stream-9-based distributions.
Resolves #755.
=> Import future annotations for pytest 6, Python 3.9 compatibility

testinfra/modules/interface.py
On Linux, implement `host.interface(iface).link()`, which returns the output of
```shell
ip --json link show $iface
```
=> testinfra/modules/interface: Implement link property

testinfra/modules/file.py
On Linux systems, if `File.mode` is used on a file that's a symlink, it will return `0x777` because that's the _mode_ of the symlink but mode is pretty meaningless for a symlink.  By doing `stat -L ...` the command will automatically resolve symlinks.
I know there is the BSDFile implementation too but I don't believe I have access to a BSD system to try things out.
This addresses a problem where testinfra is used to get information on a target file but you don't want to worry about whether a symbolic link is involved - it's irrelevant.  There are examples of symlinks in the Amazon Linux 2023 container:
```
$ docker run -it --rm amazonlinux:2023
Unable to find image 'amazonlinux:2023' locally
2023: Pulling from library/amazonlinux
1db371c0a72a: Pull complete
Digest: …
```
=> Teaching GNUFile methods to follow symlinks

images/debian_bookworm/Dockerfile
salt require timelib which require a compiler to build.
=> Fix building bookworm test image

testinfra/modules/service.py
service.exists fail with systemd because there was a typo in the underlying command, missing a space between grep option `-q` and service name.
This PR fixes that problem
This fixes #768
=> Fix service.exists

test/test_modules.py, testinfra/modules/package.py
This new logic verifies if there is a "not installed" string in the stdout when "rpm -q %s" command returns 1.
As seen in bug #758, if rpm command failed because of other reasons (such as database corruption), the old implementation was returning True, making the end-user think that the package was installed, however it was never queried.
=> Improved RpmPackage is_installed property logic.

test/test_modules.py
crypt module is being deprecated in Python 3.13 (as well as spwd). It is being used for checking host.user().password. Replacing the crypt.crypt() with hashlib or passlib would not be trivial, due to generated salt, format of shadow, etc.
=> Remove crypt lib from testing

test/test_backends.py, testinfra/backend/paramiko.py
The paramiko library has a known problem where checking the exit status can cause a deadlock if the command has written a lot of output to the stdout (or stderr) channel. We hit this problem when using `testinfra` to return data from log files during a test.
https://docs.paramiko.org/en/stable/api/channel.html#paramiko.channel.Channel.recv_exit_status
We can work around this, for the stdout case, by reading the data before checking the exit status.
I do not attempt to fix the stderr case. Fixing this would likely require a more complex fix, which reads from both stdout and stderr until they are closed, like https://stackoverflow.com/a/78765054
Here is an example of running the test case on the original code. I enabled `pytest-timeouts` with a 10 second timeout so you can see it stuck in …
=> Prevent Paramiko deadlock when test sends more than 2MB to stdout

doc/source/backends.rst
=> Extend backend documentation with a general host spec section

test/test_modules.py, testinfra/modules/mountpoint.py
`MountPoint.__repr__()` triggered a KeyError exception if the mount point doesn't exist. The commit below fixes this problem.
Solved error:
```
__________________ test_mountpoint[docker://debian_bookworm] ___________________
[gw1] linux -- Python 3.9.20 /home/runner/work/pytest-testinfra/pytest-testinfra/.tox/py39/bin/python
host = <testinfra.host.Host docker://debian_bookworm>
def test_mountpoint(host):
root_mount = host.mount_point("/")
assert root_mount.exists
assert repr(root_mount)
assert isinstance(root_mount.options, list)
assert "rw" in root_mount.options
assert root_mount.filesystem
fake_mount = host.mount_point("/fake/mount")
assert not fake_mount.exists
>       assert repr(fake_mount)
test/test_modules.py:492: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ …
```
=> Fix KeyError in MountPoint.__repr__()

testinfra/modules/service.py
A fix for this issue
https://github.com/pytest-dev/pytest-testinfra/issues/748
=> Fix systemctl is active

test/test_modules.py
I have extended some test code during a debugging session. Perhaps you would like to integrate this code into your repo.
=> Extended testing of group_names
